version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db  # Dépend du service db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: JesuisAxel!
      MYSQL_DATABASE: marieteam
      MYSQL_USER: marieteam
      MYSQL_PASSWORD: marieteam
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db           # Nom du service de la base de données
      PMA_PORT: 3306         # Port MySQL
    ports:
      - "8082:80"            # Accéder à phpMyAdmin via http://localhost:8081
    depends_on:
      - db                   # phpMyAdmin dépend de MySQL

volumes:
  db_data:
